### ISSUE TITLE
Safari: Fullscreen API not working correctly

### ISSUE THREAD

**Issue by stephenwf** [digirati-co-uk/canvas-panel#23]
There are some errors when viewing the documentation on mobile safari, related to the fullscreen API. `cannot call on of undefined` or something similar. Also potentially related, the V&A example does not load at all (probably caused by this error) and on safari desktop its very unstable, sometimes causing crashes. Lots of RAF requests (~60k per frame) might be related to OSD.

**Comment by hollyhyams** [comment]
Yes, we've also seen this in testing on mobile.
