### ISSUE TITLE
Firefox 58.0.2 - Fullscreen mode does not work

### ISSUE THREAD

**Issue by sarahos** [digirati-co-uk/canvas-panel#28]
If select a annotation and then full screen 

The annotation box remains visible but the screen goes blank, when click on blank screen the canvas appears in the bottom left corner

Need to press esc to get out of full screen

**Comment by stephenwf** [comment]
Tested this on the documentation website: https://canvas-panel.netlify.com/styleguide/#fullscreen and it did work as expected, but the V&A example does not for some reason. Still investigating cause
