### ISSUE TITLE
[improvement] Add configurable manifest caching

### ISSUE THREAD

**Issue by eelkevdbos** [digirati-co-uk/canvas-panel#610]
Currently, manifests are cached with 'force-cache' as fetch option. Making this configurable would allow for more dynamic applications that for example add annotations to the manifest in real time.

**Comment by stephenwf** [comment]
Should be deployed on NPM under version `@canvas-panel/core@pr-611` if you would like to test. I suspect I will mint a new release soon to cover the recent dependency updates and this addition. Thank you again!
