### ISSUE TITLE
Hi, I was wondering whether the functionality to view iiif audio/video content has already been implemented (ready to use) or is it not available to be used yet (in development phase)?

### ISSUE THREAD

**Issue by MImranAsghar** [digirati-co-uk/canvas-panel#689]

**Comment by stephenwf** [comment]
Hi @MImranAsghar just to summarise what we discussed on slack. We've not yet implemented AV in the viewer. The library _is_ modular though, can you could implement the AV section and use the rest of the library for handling the IIIF. 

The [Universal Viewer](http://universalviewer.io/) has some support for A/V.

**Comment by MImranAsghar** [comment]
Thanks Stephen! :)
